/** @jsxImportSource smithers-orchestrator */
import { createSmithers, Sequence, Task } from "smithers-orchestrator";
import { z } from "zod";
import { codexStructuredAgent } from "./agents";

const simpleRow = z.object({
  rowId: z.string(),
  input: z.string(),
  values: z.record(z.string(), z.string()).default({}),
});

const candidatePair = z.object({
  rowAId: z.string(),
  rowBId: z.string(),
  candidateMethod: z.string(),
  score: z.number().min(0).max(1),
  evidence: z.string(),
});

const judgedPair = z.object({
  rowAId: z.string(),
  rowBId: z.string(),
  decision: z.enum(["same", "different", "uncertain"]),
  confidence: z.number().min(0).max(1),
  reasoning: z.string(),
});

const dedupeJudgment = z.object({
  pairs: z.array(judgedPair).default([]),
});

const dedupeRow = z.object({
  rowId: z.string(),
  sourceRowId: z.string(),
  input: z.string(),
  equivalenceClassId: z.string(),
  equivalenceClassName: z.string(),
  duplicateConfidence: z.number().min(0).max(1),
  clusterReasoning: z.string(),
  selected: z.boolean(),
  synthetic: z.boolean().default(false),
  combinedFromRowIds: z.array(z.string()).default([]),
  outputRow: z.record(z.string(), z.string()).default({}),
});

const dedupeSummary = z.object({
  reportType: z.literal("dedupe"),
  objective: z.string(),
  strategy: z.string(),
  rowCount: z.number().int(),
  completedRows: z.number().int(),
  classCount: z.number().int(),
  candidatePairs: z.array(candidatePair).default([]),
  results: z.array(dedupeRow).default([]),
  citedSources: z.array(z.object({
    title: z.string().optional(),
    url: z.string().optional(),
    claim: z.string(),
  })).default([]),
});

const { Workflow, smithers, outputs } = createSmithers({
  dedupeJudgment,
  dedupeSummary,
});

export default smithers((ctx) => {
  const input = (ctx.input ?? {}) as {
    prompt?: unknown;
    objective?: unknown;
    rows?: Array<Record<string, unknown>>;
    equivalenceRelation?: unknown;
    strategy?: unknown;
    strategyPrompt?: unknown;
  };
  const objective = String(input.objective ?? input.prompt ?? "Find duplicate rows.");
  const equivalenceRelation = String(input.equivalenceRelation ?? "Rows represent the same real-world entity or record.");
  const strategy = normalizeStrategy(input.strategy);
  const rows = normalizeRows(input.rows);
  const candidatePairs = generateCandidatePairs(rows);
  const judgment = ctx.outputs.dedupeJudgment?.[0];
  const results = materializeDedupe({
    rows,
    pairs: candidatePairs,
    judgments: judgment?.pairs ?? [],
    strategy,
    strategyPrompt: String(input.strategyPrompt ?? ""),
  });
  const classCount = new Set(results.filter((row) => !row.synthetic).map((row) => row.equivalenceClassId)).size;

  return (
    <Workflow name="dedupe">
      <Sequence>
        <Task id="judge-pairs" output={outputs.dedupeJudgment} agent={codexStructuredAgent}>
          {`You judge candidate duplicate pairs for Open Superforecaster dedupe mode.

Objective:
${objective}

Equivalence relation:
${equivalenceRelation}

Candidate pairs generated by deterministic blocking:
${JSON.stringify(candidatePairs, null, 2)}

Rows:
${JSON.stringify(rows, null, 2)}

For each candidate pair, decide whether the two rows are the same under the equivalence relation. Use only the provided rows; do not use web search or external tools. Return one judgment per candidate pair. If candidatePairs is empty, return an empty pairs array.`}
        </Task>

        <Task id="summary" output={outputs.dedupeSummary} needs={{ "judge-pairs": "judge-pairs" }}>
          {{
            reportType: "dedupe",
            objective: `${objective} Relation: ${equivalenceRelation}`,
            strategy,
            rowCount: rows.length,
            completedRows: results.length,
            classCount,
            candidatePairs,
            results,
            citedSources: [],
          }}
        </Task>
      </Sequence>
    </Workflow>
  );
});

function normalizeRows(rows: Array<Record<string, unknown>> | undefined) {
  return (rows ?? [])
    .map((row, index): z.infer<typeof simpleRow> => {
      const rowId = sanitizeRowId(String(row.rowId ?? row.id ?? `row-${index + 1}`));
      const values = Object.fromEntries(
        Object.entries(row)
          .filter(([key]) => !["rowId", "id", "input", "text", "value"].includes(key))
          .map(([key, value]) => [key, valueToText(value)]),
      );
      const input = String(row.input ?? row.text ?? row.value ?? row.name ?? Object.values(values).join(" ")).trim();
      return { rowId, input, values };
    })
    .filter((row) => row.input.length > 0)
    .slice(0, 80);
}

function generateCandidatePairs(rows: Array<z.infer<typeof simpleRow>>) {
  const pairs: Array<z.infer<typeof candidatePair>> = [];
  for (let i = 0; i < rows.length; i += 1) {
    for (let j = i + 1; j < rows.length; j += 1) {
      const pair = scorePair(rows[i], rows[j]);
      if (pair) {
        pairs.push(pair);
      }
    }
  }
  return pairs.sort((a, b) => b.score - a.score).slice(0, 120);
}

function scorePair(rowA: z.infer<typeof simpleRow>, rowB: z.infer<typeof simpleRow>) {
  const normalizedA = normalizeText(rowA.input);
  const normalizedB = normalizeText(rowB.input);
  if (!normalizedA || !normalizedB) {
    return null;
  }
  if (normalizedA === normalizedB) {
    return {
      rowAId: rowA.rowId,
      rowBId: rowB.rowId,
      candidateMethod: "exact",
      score: 1,
      evidence: `Normalized row text matches exactly: ${rowA.input}`,
    };
  }
  const domainA = extractDomain(rowA.input);
  const domainB = extractDomain(rowB.input);
  if (domainA && domainA === domainB) {
    return {
      rowAId: rowA.rowId,
      rowBId: rowB.rowId,
      candidateMethod: "domain",
      score: 0.92,
      evidence: `Both rows mention domain ${domainA}.`,
    };
  }
  const similarity = tokenSimilarity(normalizedA, normalizedB);
  if (similarity >= 0.34) {
    return {
      rowAId: rowA.rowId,
      rowBId: rowB.rowId,
      candidateMethod: "fuzzy",
      score: Math.round(similarity * 100) / 100,
      evidence: `Token overlap between "${rowA.input}" and "${rowB.input}".`,
    };
  }
  return null;
}

function materializeDedupe(input: {
  rows: Array<z.infer<typeof simpleRow>>;
  pairs: Array<z.infer<typeof candidatePair>>;
  judgments: Array<z.infer<typeof judgedPair>>;
  strategy: "identify" | "select" | "combine";
  strategyPrompt: string;
}) {
  const parent = new Map(input.rows.map((row) => [row.rowId, row.rowId]));
  const confidenceByClassEdge = new Map<string, number>();
  const reasoningByClassEdge = new Map<string, string>();

  for (const judgment of input.judgments) {
    if (judgment.decision === "same" && judgment.confidence >= 0.6) {
      union(parent, judgment.rowAId, judgment.rowBId);
      confidenceByClassEdge.set(edgeKey(judgment.rowAId, judgment.rowBId), judgment.confidence);
      reasoningByClassEdge.set(edgeKey(judgment.rowAId, judgment.rowBId), judgment.reasoning);
    }
  }

  const classes = new Map<string, Array<z.infer<typeof simpleRow>>>();
  for (const row of input.rows) {
    const root = find(parent, row.rowId);
    classes.set(root, [...(classes.get(root) ?? []), row]);
  }

  const outputRows: Array<z.infer<typeof dedupeRow>> = [];
  for (const [classRoot, classRows] of classes.entries()) {
    const canonical = chooseCanonical(classRows);
    const classId = `class-${sanitizeRowId(classRoot)}`;
    const duplicateConfidence = classRows.length === 1 ? 1 : classConfidence(classRows, confidenceByClassEdge);
    const clusterReasoning = classRows.length === 1
      ? "Singleton row; no duplicate candidate passed the judgment threshold."
      : classReasoning(classRows, reasoningByClassEdge);

    for (const row of classRows) {
      outputRows.push({
        rowId: row.rowId,
        sourceRowId: row.rowId,
        input: row.input,
        equivalenceClassId: classId,
        equivalenceClassName: canonical.input,
        duplicateConfidence,
        clusterReasoning,
        selected: input.strategy === "identify" ? true : row.rowId === canonical.rowId,
        synthetic: false,
        combinedFromRowIds: [],
        outputRow: {
          rowId: row.rowId,
          input: row.input,
          ...row.values,
        },
      });
    }

    if (input.strategy === "combine" && classRows.length > 1) {
      outputRows.push({
        rowId: `${classId}-combined`,
        sourceRowId: `${classId}-combined`,
        input: canonical.input,
        equivalenceClassId: classId,
        equivalenceClassName: canonical.input,
        duplicateConfidence,
        clusterReasoning: `${clusterReasoning}${input.strategyPrompt ? ` Combine instruction: ${input.strategyPrompt}` : ""}`,
        selected: true,
        synthetic: true,
        combinedFromRowIds: classRows.map((row) => row.rowId),
        outputRow: combineRows(classRows),
      });
    }
  }

  return outputRows;
}

function chooseCanonical(rows: Array<z.infer<typeof simpleRow>>) {
  return [...rows].sort((a, b) => completeness(b) - completeness(a) || a.rowId.localeCompare(b.rowId))[0];
}

function completeness(row: z.infer<typeof simpleRow>) {
  return row.input.length + Object.values(row.values).filter(Boolean).length * 20;
}

function combineRows(rows: Array<z.infer<typeof simpleRow>>) {
  const combined: Record<string, string> = {
    combinedFromRowIds: rows.map((row) => row.rowId).join(" | "),
  };
  for (const row of rows) {
    for (const [key, value] of Object.entries({ input: row.input, ...row.values })) {
      if (!value) {
        continue;
      }
      combined[key] = combined[key] ? joinUnique(combined[key], value) : value;
    }
  }
  return combined;
}

function classConfidence(rows: Array<z.infer<typeof simpleRow>>, confidenceByEdge: Map<string, number>) {
  const values = [];
  for (let i = 0; i < rows.length; i += 1) {
    for (let j = i + 1; j < rows.length; j += 1) {
      const value = confidenceByEdge.get(edgeKey(rows[i].rowId, rows[j].rowId));
      if (typeof value === "number") {
        values.push(value);
      }
    }
  }
  return values.length ? Math.round((values.reduce((sum, value) => sum + value, 0) / values.length) * 100) / 100 : 0.6;
}

function classReasoning(rows: Array<z.infer<typeof simpleRow>>, reasoningByEdge: Map<string, string>) {
  const reasons = [];
  for (let i = 0; i < rows.length; i += 1) {
    for (let j = i + 1; j < rows.length; j += 1) {
      const reason = reasoningByEdge.get(edgeKey(rows[i].rowId, rows[j].rowId));
      if (reason) {
        reasons.push(reason);
      }
    }
  }
  return reasons.length ? reasons.join(" | ") : "Rows were grouped by accepted duplicate-pair judgments.";
}

function union(parent: Map<string, string>, a: string, b: string) {
  parent.set(find(parent, b), find(parent, a));
}

function find(parent: Map<string, string>, value: string): string {
  const current = parent.get(value) ?? value;
  if (current === value) {
    return current;
  }
  const root = find(parent, current);
  parent.set(value, root);
  return root;
}

function edgeKey(a: string, b: string) {
  return [a, b].sort().join(":");
}

function joinUnique(existing: string, next: string) {
  const values = new Set(existing.split(" | ").concat(next));
  return [...values].join(" | ");
}

function tokenSimilarity(left: string, right: string) {
  const leftTokens = new Set(left.split(" ").filter(Boolean));
  const rightTokens = new Set(right.split(" ").filter(Boolean));
  const intersection = [...leftTokens].filter((token) => rightTokens.has(token)).length;
  const union = new Set([...leftTokens, ...rightTokens]).size;
  return union ? intersection / union : 0;
}

function normalizeText(value: string) {
  return value.toLowerCase().replace(/https?:\/\//g, "").replace(/[^a-z0-9.]+/g, " ").replace(/\b(inc|llc|ltd|limited|corp|corporation|company|co)\b/g, "").trim();
}

function extractDomain(value: string) {
  const match = value.toLowerCase().match(/\b(?:https?:\/\/)?(?:www\.)?([a-z0-9-]+\.[a-z]{2,})(?:\/|\b)/);
  return match?.[1] ?? null;
}

function valueToText(value: unknown) {
  if (value === null || value === undefined) {
    return "";
  }
  if (typeof value === "object") {
    return JSON.stringify(value);
  }
  return String(value);
}

function normalizeStrategy(value: unknown): "identify" | "select" | "combine" {
  const strategy = String(value ?? "identify");
  if (strategy === "select" || strategy === "combine") {
    return strategy;
  }
  return "identify";
}

function sanitizeRowId(value: string) {
  const sanitized = value.toLowerCase().replace(/[^a-z0-9_-]+/g, "-").replace(/^-+|-+$/g, "");
  return sanitized || "row";
}
