/** @jsxImportSource smithers-orchestrator */
import { createSmithers, Sequence, Task } from "smithers-orchestrator";
import { z } from "zod";
import { codexStructuredAgent } from "./agents";

const simpleRow = z.object({
  rowId: z.string(),
  input: z.string(),
  values: z.record(z.string(), z.string()).default({}),
});

const candidateEdge = z.object({
  leftRowId: z.string(),
  rightRowId: z.string(),
  candidateMethod: z.string(),
  score: z.number().min(0).max(1),
  evidence: z.string(),
});

const judgedEdge = z.object({
  leftRowId: z.string(),
  rightRowId: z.string(),
  decision: z.enum(["match", "not_match", "uncertain"]),
  confidence: z.number().min(0).max(1),
  reasoning: z.string(),
});

const mergeJudgment = z.object({
  edges: z.array(judgedEdge).default([]),
});

const mergeRow = z.object({
  rowId: z.string(),
  leftRowId: z.string(),
  input: z.string(),
  matchedRightRowIds: z.array(z.string()).default([]),
  matchStatus: z.enum(["exact", "fuzzy", "llm", "unmatched", "conflict"]),
  matchConfidence: z.number().min(0).max(1),
  matchReasoning: z.string(),
  joinedRow: z.record(z.string(), z.string()).default({}),
});

const mergeSummary = z.object({
  reportType: z.literal("merge"),
  objective: z.string(),
  relationshipType: z.string(),
  rowCount: z.number().int(),
  completedRows: z.number().int(),
  mergeBreakdown: z.record(z.string(), z.number()),
  candidateEdges: z.array(candidateEdge).default([]),
  results: z.array(mergeRow).default([]),
  citedSources: z.array(z.object({
    title: z.string().optional(),
    url: z.string().optional(),
    claim: z.string(),
  })).default([]),
});

const { Workflow, smithers, outputs } = createSmithers({
  mergeJudgment,
  mergeSummary,
});

export default smithers((ctx) => {
  const input = (ctx.input ?? {}) as {
    prompt?: unknown;
    objective?: unknown;
    task?: unknown;
    leftRows?: Array<Record<string, unknown>>;
    rightRows?: Array<Record<string, unknown>>;
    leftKey?: unknown;
    rightKey?: unknown;
    relationshipType?: unknown;
  };
  const objective = String(input.objective ?? input.task ?? input.prompt ?? "Merge left rows against right rows.");
  const relationshipType = String(input.relationshipType ?? "many_to_one");
  const leftRows = normalizeRows(input.leftRows, "left");
  const rightRows = normalizeRows(input.rightRows, "right");
  const candidates = generateCandidates({
    leftRows,
    rightRows,
    leftKey: optionalString(input.leftKey),
    rightKey: optionalString(input.rightKey),
  });
  const judgment = ctx.outputs.mergeJudgment?.[0];
  const results = materializeMerge({
    leftRows,
    rightRows,
    candidates,
    judgedEdges: judgment?.edges ?? [],
    relationshipType,
  });

  return (
    <Workflow name="merge">
      <Sequence>
        <Task id="judge-candidates" output={outputs.mergeJudgment} agent={codexStructuredAgent}>
          {`You judge candidate row matches for Open Superforecaster merge mode.

Objective:
${objective}

Relationship type:
${relationshipType}

Candidate edges generated by deterministic exact/fuzzy blocking:
${JSON.stringify(candidates, null, 2)}

Left rows:
${JSON.stringify(leftRows, null, 2)}

Right rows:
${JSON.stringify(rightRows, null, 2)}

For each candidate edge, decide whether the rows represent the same intended entity or record for this merge task. Use only the provided rows; do not use web search or external tools. Return one judgment per candidate edge. If candidates are empty, return an empty edges array.`}
        </Task>

        <Task id="summary" output={outputs.mergeSummary} needs={{ "judge-candidates": "judge-candidates" }}>
          {{
            reportType: "merge",
            objective,
            relationshipType,
            rowCount: leftRows.length,
            completedRows: results.length,
            mergeBreakdown: countMergeBreakdown(results),
            candidateEdges: candidates,
            results,
            citedSources: [],
          }}
        </Task>
      </Sequence>
    </Workflow>
  );
});

function normalizeRows(rows: Array<Record<string, unknown>> | undefined, prefix: string) {
  return (rows ?? [])
    .map((row, index): z.infer<typeof simpleRow> => {
      const rowId = sanitizeRowId(String(row.rowId ?? row.id ?? `${prefix}-${index + 1}`));
      const values = Object.fromEntries(
        Object.entries(row)
          .filter(([key]) => !["rowId", "id", "input", "text", "value"].includes(key))
          .map(([key, value]) => [key, valueToText(value)]),
      );
      const input = String(row.input ?? row.text ?? row.value ?? row.name ?? Object.values(values).join(" ")).trim();
      return { rowId, input, values };
    })
    .filter((row) => row.input.length > 0)
    .slice(0, 50);
}

function generateCandidates(input: {
  leftRows: Array<z.infer<typeof simpleRow>>;
  rightRows: Array<z.infer<typeof simpleRow>>;
  leftKey: string | null;
  rightKey: string | null;
}) {
  const edges: Array<z.infer<typeof candidateEdge>> = [];
  for (const left of input.leftRows) {
    const scored = input.rightRows
      .map((right) => scorePair(left, right, input.leftKey, input.rightKey))
      .filter((edge): edge is z.infer<typeof candidateEdge> => edge !== null)
      .sort((a, b) => b.score - a.score)
      .slice(0, 4);
    edges.push(...scored);
  }
  return edges.slice(0, 80);
}

function scorePair(
  left: z.infer<typeof simpleRow>,
  right: z.infer<typeof simpleRow>,
  leftKey: string | null,
  rightKey: string | null,
) {
  const leftText = keyOrInput(left, leftKey);
  const rightText = keyOrInput(right, rightKey);
  const normalizedLeft = normalizeText(leftText);
  const normalizedRight = normalizeText(rightText);
  if (!normalizedLeft || !normalizedRight) {
    return null;
  }
  if (normalizedLeft === normalizedRight) {
    return {
      leftRowId: left.rowId,
      rightRowId: right.rowId,
      candidateMethod: "exact",
      score: 1,
      evidence: `Normalized key/text matches exactly: ${leftText}`,
    };
  }
  const domainLeft = extractDomain(leftText);
  const domainRight = extractDomain(rightText);
  if (domainLeft && domainLeft === domainRight) {
    return {
      leftRowId: left.rowId,
      rightRowId: right.rowId,
      candidateMethod: "domain",
      score: 0.92,
      evidence: `Both rows mention domain ${domainLeft}.`,
    };
  }
  const similarity = tokenSimilarity(normalizedLeft, normalizedRight);
  if (similarity >= 0.34) {
    return {
      leftRowId: left.rowId,
      rightRowId: right.rowId,
      candidateMethod: "fuzzy",
      score: Math.round(similarity * 100) / 100,
      evidence: `Token overlap between "${leftText}" and "${rightText}".`,
    };
  }
  return null;
}

function materializeMerge(input: {
  leftRows: Array<z.infer<typeof simpleRow>>;
  rightRows: Array<z.infer<typeof simpleRow>>;
  candidates: Array<z.infer<typeof candidateEdge>>;
  judgedEdges: Array<z.infer<typeof judgedEdge>>;
  relationshipType: string;
}) {
  const rightById = new Map(input.rightRows.map((row) => [row.rowId, row]));
  const candidateByKey = new Map(input.candidates.map((edge) => [`${edge.leftRowId}:${edge.rightRowId}`, edge]));
  const judgedMatches = input.judgedEdges
    .filter((edge) => edge.decision === "match" && edge.confidence >= 0.55)
    .sort((a, b) => b.confidence - a.confidence);
  const usedRight = new Set<string>();

  return input.leftRows.map((left) => {
    const eligible = judgedMatches.filter((edge) => edge.leftRowId === left.rowId);
    const chosen = [];
    for (const edge of eligible) {
      if (input.relationshipType === "one_to_one" && usedRight.has(edge.rightRowId)) {
        continue;
      }
      chosen.push(edge);
      usedRight.add(edge.rightRowId);
      if (!["one_to_many", "many_to_many"].includes(input.relationshipType)) {
        break;
      }
    }
    const matchedRightRows = chosen.map((edge) => rightById.get(edge.rightRowId)).filter((row): row is z.infer<typeof simpleRow> => Boolean(row));
    const best = chosen[0];
    const bestCandidate = best ? candidateByKey.get(`${best.leftRowId}:${best.rightRowId}`) : null;
    const status = best ? (bestCandidate?.candidateMethod === "exact" ? "exact" : "llm") : "unmatched";
    return {
      rowId: left.rowId,
      leftRowId: left.rowId,
      input: left.input,
      matchedRightRowIds: chosen.map((edge) => edge.rightRowId),
      matchStatus: status as "exact" | "fuzzy" | "llm" | "unmatched" | "conflict",
      matchConfidence: best?.confidence ?? 0,
      matchReasoning: best?.reasoning ?? "No matching right row met the confidence threshold.",
      joinedRow: {
        ...prefixValues("left", left),
        ...joinRightValues(matchedRightRows),
      },
    };
  });
}

function countMergeBreakdown(results: Array<z.infer<typeof mergeRow>>) {
  const counts: Record<string, number> = { exact: 0, fuzzy: 0, llm: 0, unmatched: 0, conflict: 0 };
  for (const result of results) {
    counts[result.matchStatus] = (counts[result.matchStatus] ?? 0) + 1;
  }
  return counts;
}

function keyOrInput(row: z.infer<typeof simpleRow>, key: string | null) {
  return key ? row.values[key] ?? row.input : row.input;
}

function prefixValues(prefix: string, row: z.infer<typeof simpleRow>) {
  return Object.fromEntries(Object.entries({ rowId: row.rowId, input: row.input, ...row.values }).map(([key, value]) => [`${prefix}.${key}`, value]));
}

function joinRightValues(rows: Array<z.infer<typeof simpleRow>>) {
  const merged: Record<string, string> = {};
  for (const row of rows) {
    for (const [key, value] of Object.entries(prefixValues("right", row))) {
      merged[key] = merged[key] ? `${merged[key]} | ${value}` : value;
    }
  }
  return merged;
}

function tokenSimilarity(left: string, right: string) {
  const leftTokens = new Set(left.split(" ").filter(Boolean));
  const rightTokens = new Set(right.split(" ").filter(Boolean));
  const intersection = [...leftTokens].filter((token) => rightTokens.has(token)).length;
  const union = new Set([...leftTokens, ...rightTokens]).size;
  return union ? intersection / union : 0;
}

function normalizeText(value: string) {
  return value.toLowerCase().replace(/https?:\/\//g, "").replace(/[^a-z0-9.]+/g, " ").replace(/\b(inc|llc|ltd|limited|corp|corporation|company|co)\b/g, "").trim();
}

function extractDomain(value: string) {
  const match = value.toLowerCase().match(/\b(?:https?:\/\/)?(?:www\.)?([a-z0-9-]+\.[a-z]{2,})(?:\/|\b)/);
  return match?.[1] ?? null;
}

function valueToText(value: unknown) {
  if (value === null || value === undefined) {
    return "";
  }
  if (typeof value === "object") {
    return JSON.stringify(value);
  }
  return String(value);
}

function optionalString(value: unknown) {
  const text = String(value ?? "").trim();
  return text || null;
}

function sanitizeRowId(value: string) {
  const sanitized = value.toLowerCase().replace(/[^a-z0-9_-]+/g, "-").replace(/^-+|-+$/g, "");
  return sanitized || "row";
}
